name: main
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: Config Git
        run: |
          mkdir -p ~/.ssh/
          echo '${{ secrets.GITHUB1_PRIVATE_KEY }}' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name "random-bot"
          git config --global user.email  "random-bot@bot"
      - name: Commit
        run: |
          filename=$(date +%s%N)
          "date" | ssh-keygen -f ./data/$(filename)
          git add *
          git commit -m $(filename)
          git push origin main
