name: main
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: Config Git
        run: |
          mkdir -p ~/.ssh/
          echo '${{ secrets.GITHUB1_PRIVATE_KEY }}' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name '${{ secrets.GITHUB1_NAME }}'
          git config --global user.email '${{ secrets.GITHUB1_EMAIL }}'
      - name: Commit
        run: |
          echo "$(date +%s%N)" > ./data/$(date +%s%N)
          git add *
          git commit -m $(date +%s%N)
          git push origin main
